---
- name: Create folder for {{asdasd}} tests (var not resolved)
  command: echo 1

- name: "Role defaults var {{role_defaults_var|default(3)}}"
  command: echo {{role_defaults_var}}

- name: Var from role incluzzzion {{role_inc_var}}
  command: echo {{role_inc_var}}

- name: Var from super role {{role_super_var}} defaults
  command: echo {{role_super_var}}

- name: Var from playbook {{role_playbook_var}}
  command: echo {{role_playbook_var}}

- name: Var from role_super_and_inc_var {{role_super_and_inc_var}}
  command: echo {{role_super_and_inc_var}}

- name: Var from role_super_and_sub_var {{role_super_and_sub_var}}
  command: echo {{role_super_and_sub_var}}

- name: Var from local_super_var2 {{local_super_var2}}
  command: echo {{local_super_var2}}
